//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVL_Kyc
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.cvlkra.com/", ConfigurationName="CVL_Kyc.PANInquirySoap")]
    public interface PANInquirySoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.cvlkra.com/GetPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> GetPasswordAsync(string password, string PassKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.cvlkra.com/GetPanStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> GetPanStatusAsync(string panNo, string userName, string PosCode, string password, string PassKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.cvlkra.com/RTAPANDataDownload", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> RTAPANDataDownloadAsync(string inputXML, string userName, string PosCode, string password, string PassKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.cvlkra.com/RTAPANDataDownload_XMLDoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> RTAPANDataDownload_XMLDocAsync(string inputXML, string userName, string PosCode, string password, string PassKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.cvlkra.com/InsertUpdateKYCRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> InsertUpdateKYCRecordAsync(string inputXML, string userName, string PosCode, string password, string PassKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.cvlkra.com/SolicitPANDetailsFetchALLKRA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.XmlNode> SolicitPANDetailsFetchALLKRAAsync(string inputXML, string userName, string PosCode, string password, string PassKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface PANInquirySoapChannel : CVL_Kyc.PANInquirySoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class PANInquirySoapClient : System.ServiceModel.ClientBase<CVL_Kyc.PANInquirySoap>, CVL_Kyc.PANInquirySoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PANInquirySoapClient(EndpointConfiguration endpointConfiguration) : 
                base(PANInquirySoapClient.GetBindingForEndpoint(endpointConfiguration), PANInquirySoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PANInquirySoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PANInquirySoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PANInquirySoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PANInquirySoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PANInquirySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> GetPasswordAsync(string password, string PassKey)
        {
            return base.Channel.GetPasswordAsync(password, PassKey);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> GetPanStatusAsync(string panNo, string userName, string PosCode, string password, string PassKey)
        {
            return base.Channel.GetPanStatusAsync(panNo, userName, PosCode, password, PassKey);
        }
        
        public System.Threading.Tasks.Task<string> RTAPANDataDownloadAsync(string inputXML, string userName, string PosCode, string password, string PassKey)
        {
            return base.Channel.RTAPANDataDownloadAsync(inputXML, userName, PosCode, password, PassKey);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> RTAPANDataDownload_XMLDocAsync(string inputXML, string userName, string PosCode, string password, string PassKey)
        {
            return base.Channel.RTAPANDataDownload_XMLDocAsync(inputXML, userName, PosCode, password, PassKey);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> InsertUpdateKYCRecordAsync(string inputXML, string userName, string PosCode, string password, string PassKey)
        {
            return base.Channel.InsertUpdateKYCRecordAsync(inputXML, userName, PosCode, password, PassKey);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> SolicitPANDetailsFetchALLKRAAsync(string inputXML, string userName, string PosCode, string password, string PassKey)
        {
            return base.Channel.SolicitPANDetailsFetchALLKRAAsync(inputXML, userName, PosCode, password, PassKey);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PANInquirySoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.PANInquirySoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PANInquirySoap))
            {
                return new System.ServiceModel.EndpointAddress("http://www.cvlkra.com/PANInquiry.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.PANInquirySoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://www.cvlkra.com/PANInquiry.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            PANInquirySoap,
            
            PANInquirySoap12,
        }
    }
}
